#!/usr/bin/perl -U

# Create a package file for mirror and mirror home pages of users.
# Call: homepage [client | user]

my $TmpDir = "/tmp";
my $Target = "webout";
my $TargetDir = "/math";
# temporary
my $Rmirror = "/home/www/mirror-2.9/mirror";

my $client = "";
my %Proxied = ();

# Initialization and argument handling

my $defaults = "/home/www/Webout/homepage_defaults";
my $distfile = "$TmpDir/mirror-" . getppid();
`/usr/bin/rm -f $distfile`;
open(DISTFILE, ">$distfile") or die "Can't open $distfile";

open(DEFAULTS, "$defaults") or die "Can't open $defaults";
while (<DEFAULTS>) {
  print DISTFILE $_;
}
close DEFAULTS;

my $auto;

my @Auto = `cat /home/www/Webout/auto.homej`;

my $argument = shift;

my $only = $< eq "root" ? "" : $< ;
if ($only) {
  $only = $argument ? $argument : getpwuid($only);
}
else {
  $client = $argument;
  if (!$only) {
      foreach $auto (@Auto) {
	  my ($uid, $rest) =
	      split(/\s/, $auto);
	  my ($home, $sdir, $udir, $proxy) =
	      split(/:/, $rest);
	  if ($proxy) {
	      $Proxied{$home} = $proxy;
	  }
      }
  }
}

my $sysname = (($client and not $Proxied{$client}) ?
    "rsh $client " : "") . "uname -ns";
my ($system, $name) =
  split(/\s/, `$sysname`);
$name =~ s/^(.*)\.wisdom\.weizmann\.ac\.il$/$1/;

# Main loop

foreach $auto (@Auto) {
  my ($uid, $rest) =
    split(/\s/, $auto);
  my ($home, $sdir, $udir, $proxy) =
    split(/:/, $rest);
  my $homedir = ($only || $client || $proxy) && ($home ne $name) ?
      					       "/home/$uid" : "$sdir/$udir";
  my $pubdir = "$homedir/public_html";

  if ($client && ($client ne $home)) {
      next
  }
  if (not((-r "$homedir/public_html/index.html") ||
	  (-r "$homedir/public_html/index.php"))) {
      open(PUBINX, "$pubdir/index.html") or
	 (open(PUBINX, "$pubdir/index.php") or next);
      close(PUBINX);
  }
  if ($only eq $uid || (!$only && ($proxy || $home eq $name))) {
    if (-l $pubdir && (!$only || $only eq $uid)) {
      my $redir = readlink($pubdir);
      if ($redir) {
	if ($redir =~ /^\//) {
	  $pubdir = $redir;
	}
	else {
	  $pubdir = "$homedir/$redir";
	}
      }
      else {
	next;
      }
    }
    print DISTFILE "package=$uid\n"
                 . "\tremote_dir=$TargetDir/$uid\n"
                 . "\tlocal_dir=$homedir/public_html/\n";
  }
}
close DISTFILE or die "Can't close $distfile";

# Now call mirror and remove the distfile.

my $result = `$Rmirror $distfile`;
if ($only) {
  print $result;
}
 `/usr/bin/rm -f $distfile`;

# The End
