#!/bin/sh
#echo
/home/www/Webout/auto_homes -esedna,narkis /home/www/Webout/mhomepages
# Users from sedna and narkis are executed locally on nufar.
/home/www/Webout/auto_homes -ssedna,narkis /home/www/Webout/mhomepages
