#!/bin/csh
/home/www/mirror-2.9/mirror /home/www/Webout/mirror-seminars
echo "user math m0th12 ">tttttttt
echo "cd /math/Seminars" >>tttttttt
echo "lcd /home/system/Seminars" >>tttttttt
echo "put sem_sched.dat "  >> tttttttt
echo "close" >> tttttttt
echo "bye" >> tttttttt
ftp -n webout<tttttttt
/bin/rm tttttttt 
